# Generated by Django 5.1.7 on 2025-03-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='program_link',
        ),
    ]
