# Generated by Django 5.1.7 on 2025-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_program_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default=2, upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
