# Generated by Django 5.1.7 on 2025-03-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_category_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
