# Generated by Django 5.2.1 on 2025-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
