# Generated by Django 5.2.1 on 2025-05-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventimage_caption_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report',
            field=models.TextField(blank=True, help_text='Отчёт о том, как прошло мероприятие', null=True),
        ),
    ]
