# Generated by Django 5.2.1 on 2025-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='report_en',
            field=models.TextField(blank=True, help_text='Отчёт о том, как прошло мероприятие', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='report_kk',
            field=models.TextField(blank=True, help_text='Отчёт о том, как прошло мероприятие', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='report_ru',
            field=models.TextField(blank=True, help_text='Отчёт о том, как прошло мероприятие', null=True),
        ),
    ]
